name: Running build checks

on:
  pull_request:
    branches:
      - main

jobs:
  build-app:
    needs: [build-sdk]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Run app build
        run: yarn workspace @fullstack-devtool/app make

  build-sdk:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Run sdk build
        run: yarn workspace @fullstack-devtool/sdk build
