on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Run Release Please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      app_release_created: ${{ steps.release-please.outputs['packages/app--release_created'] }}
      sdk_release_created: ${{ steps.release-please.outputs['packages/sdk--release_created'] }}

    steps:
      - uses: actions/checkout@v4

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install --frozen-lockfile

      - name: Build SDK and FSDT app
        run: yarn build

      - run: echo ${{secrets.NPM_TOKEN}}

      - name: Publish sdk
        if: ${{ steps.release.outputs.sdk_release_created }}
        run: yarn publish:sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish app
        if: ${{ steps.release.outputs.app_release_created }}
        run: yarn publish:app
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
