name: Running tests

on:
  pull_request:
    branches:
      - main

jobs:
  test-spell:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Run spell check
        run: yarn test:spelling
  test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Run eslint
        run: yarn test:lint
  test-format:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Run Prettier
        run: yarn test:format
